//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyTitle("Resharper.Bootstrap3.Templates")]
[assembly: AssemblyVersion("2017.1.0")]
[assembly: AssemblyFileVersion("2017.1.0")]

