image: Visual Studio 2019
    
skip_branch_with_pr: true
skip_tags: true

test: off

build_script:
- cmd: >-

    build.cmd --target UpdateBuildVersion

    build.cmd --target UploadArtifact --bootstrapVersion 3 --configuration Release

    build.cmd --target UploadArtifact --bootstrapVersion 4 --configuration Release
