image: Visual Studio 2019
build_script:
- cmd: >-

    build.cmd --target UpdateBuildVersion

    build.cmd --target UploadArtifact --bootstrapVersion 3 --configuration Release

    build.cmd --target UploadArtifact --bootstrapVersion 4 --configuration Release
    
test: off
